### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by magick93** [mraniki/cefi#404]
Hi

Firstly, thanks for sharing this. It looks really interesting. I've been considering making a IB profile for ccxt for a while. 

I'm wondering, how would I use cefi in place of ccxt - eg, if I'm using a project that currently uses ccx type, is there a recommended approach to using cefi, that doesnt require doing a find and replace throughout the code - or is this essentially just another exchange supported by ccxt?

**Comment by mraniki** [comment]
Hey @magick93 Thanks for your interest! the library allow you to interact with CCXT centralised exchange (mostly crypto), Interactive broker (via ib_sync library) and I'm testing capital.com api. 

2 way to use it:

1.  Directly in your own app/bot: https://github.com/mraniki/cefi/blob/main/examples/example.py

```
    cex = CexTrader()
    await cex.get_account_balances()
```

2. or you can use https://github.com/mraniki/tt that I built to interact with cefi or defi via a messaging platform 

whatever the options, the settings are set the same way: 
 https://github.com/mraniki/cefi/blob/main/cefi/default_settings.toml

- create a settings.toml and add the info for your platform IBKR or crypto exchange via CCXT:
`
[default.cex.ibkr]
protocol = "ib"
name = ""
user_id = ""
api_key= ""
host = ""
port = 7497
secret= ""
password = ""
testmode = true
broker_client_id = ""
broker_account_number = ""
broker_gateway = true


[default.cex.binance]
protocol = "ccxt"
name = "binance"
user_id = ""
api_key= ""
secret=""
testmode = true
defaulttype = "spot"
ordertype = "market"

`
Head over the wiki for more details on the settings https://talky.readthedocs.io/en/latest/02_config.html

**Comment by mraniki** [comment]
Yes it is a wrapper to ccxt, ib_sync and capital_com. The wrapper try to have common methods like fetching balance or placing order regardless of library to manage multiple exchange regardless of their library. If you only use crypto And centralized exchange with direct call, ccxt could be sufficient for your need.

if you look at tt, https://github.com/mraniki/tt, I built cefi to wrap all centralized exchanges under cefi library.
Hope that helps.

**Comment by magick93** [comment]
> If you only use crypto And centralized exchange with direct call, ccxt could be sufficient for your need.

Actually I'm interested in experimenting with equities on some of the innovative crypto trading platforms.

**Comment by mraniki** [comment]
Do you have an example? Not sure if ccxt covered it but would to check it.

**Comment by magick93** [comment]
Yes, take a look at https://github.com/freqtrade/freqtrade

They way they use ccxt is very similar to other projects, like https://github.com/Drakkar-Software/OctoBot.

**Comment by mraniki** [comment]
no sorry I meant with crypto exchange provide equities and have ccxt integrated ?

**Comment by magick93** [comment]
Oh, no. I' dont know of any of crypto exchanges that also offer equities. 

That is why I want to use IBFX - so I can use the crypto trading platforms, such as freqtrade etc but with a traditional equities broker like IB.

**Comment by mraniki** [comment]
Understood. Have a look at the docs and let me know if you have any question. Now I’m finalizing the capital.com integration so that will be another broker added which do multi assets.
