### ISSUE TITLE
Broker - Capital.com 

### ISSUE THREAD

**Issue by mraniki** [mraniki/cefi#409]

**Comment by mraniki** [comment]
initial interface setup

**Comment by mraniki** [comment]
Balance, order execution and position implemented.

**Comment by Kamvia** [comment]
Hy there .   Is  there  a   way  to  reduce the  position  in normal  mode  and  hedge  mode ?   Doesnt  seems  clear  from   api docs .
 On using  normal mode  and  placing an  reverse smaller  order  it  reduce the position  ,  but  it  will update  the entry  price  of the initial position  to  the  tp   price ,  and  that  is not the  desired  behaviour. In    mobile app  it  different 
 Thanks

**Comment by mraniki** [comment]
No so far I only implemented the placing order and quote function and I’m using it in hedge mode. Let me check if we can implement that @Kamvia

**Comment by Kamvia** [comment]
![Screenshot_20240428-113336_WhatsApp](https://github.com/mraniki/cefi/assets/150781467/d887fd82-8d4e-4249-ab77-6eb15afac64c)
  This response  fron their  support ,  not  dev team member

**Comment by Kamvia** [comment]
I can  confirm  that  reducing  position  works  in  normal mode ,  by placing     an  order  in the oposite  side smaller  amount

**Comment by Kamvia** [comment]
How  can  i  contact you ? 
  Could  you post  some  contact details  please ?

**Comment by mraniki** [comment]
What info do you need @Kamvia ?

**Comment by Kamvia** [comment]
Some     to  talk  fluently..  email,  skype    telegram , or  any  other  messaging platform

**Comment by mraniki** [comment]
@Kamvia  you can use the discussion area here https://github.com/mraniki/tt/discussions or masto on my profile

**Comment by Kamvia** [comment]
Ok. Thanks
