### ISSUE TITLE
Capital com multiple instances 

### ISSUE THREAD

**Issue by Kamvia** [mraniki/cefi#477]
Even if  we  use  1  api with  multiple   subacounts or multiple  api  each  one  with  his  coresponding subaccount , we  enter in  a race  condition  for  prefered  account , that  could be  changed  from  anywhere  and  anytime   by  another  class instance 
  We   must  implement  lock   and  release   to  acquire   preferred  account,   on  order  execution  based on  subaccount  id

**Comment by mraniki** [comment]
So to force/predefine a subaccount as self.account for that client?

**Comment by Kamvia** [comment]
My  aproach is   : 
 Self.accountId   set
 in  a   create position  method  ,  (that require  specific  accountId ) i lock  the  account  switch , 
 check  if  active account ==   to accountId 
If  not   ,  switch  to  that  accountId   ,  make it  preferred 
 Place the order 
Release  the  lock

.. not  the  optimal  way , ( it  has  network  request  , if  accounts  dont  match ) ..
  Maybe  we   get some  better  response  from  capital  team ,  or they force bound   some  api  account to   certain  accountId ..
  Everything  is  fine  in   a  single  api ,   single  subaccount.  But  shit  happens  when  multiple  accounts  with 1 api or multiple  apis

**Comment by mraniki** [comment]
Yes I think I see it do you have a pr ready? Else I will check that in coming days

**Comment by mraniki** [comment]
@Kamvia i did a quick pr and added a new settting default_account. Not fully tested yet on my side but give a try.

**Comment by Kamvia** [comment]
Nope.
We must  use  Sequence IDs and Semaphores

Sequence IDs: Labeling each event with a unique sequence ID can help you track and manage events in the correct order, ensuring that each operation is handled properly.

Semaphores: Semaphores can be used to control access to a resource, allowing a set number of threads to access a shared resource simultaneously, which helps prevent race conditions.

**Comment by mraniki** [comment]
@Kamvia not sure to follow. Shoot a pr and we can go further.
